version: '2.4'

services:
  octoprint1:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 9001:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
      - v_octoprint1:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0

  octoprint2:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 9002:80
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/video2:/dev/video2
    volumes:
      - v_octoprint2:/octoprint

    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video2
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - PGID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  v_octoprint1:
  v_octoprint2:
